# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestCenital():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testCenital(self):
    # Test name: Test Cenital
    # Step # | name | target | value
    # 1 | open | /sumate/ | 
    self.driver.get("https://cenital.com/sumate/")
    # 2 | setWindowSize | 795x703 | 
    self.driver.set_window_size(795, 703)
    # 3 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 4 | runScript | window.scrollTo(0,48) | 
    self.driver.execute_script("window.scrollTo(0,48)")
    # 5 | click | id=wpforms-4543-field_0 | 
    self.driver.find_element(By.ID, "wpforms-4543-field_0").click()
    # 6 | type | id=wpforms-4543-field_0 | Juan Jose Perez
    self.driver.find_element(By.ID, "wpforms-4543-field_0").send_keys("Juan Jose Perez")
    # 7 | type | id=wpforms-4543-field_1 | abcdefg@hola.com
    self.driver.find_element(By.ID, "wpforms-4543-field_1").send_keys("abcdefg@hola.com")
    # 8 | mouseDown | id=wpforms-4543-field_2 | 
    element = self.driver.find_element(By.ID, "wpforms-4543-field_2")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 9 | mouseUp | css=#wpforms-4543-field_2-container > .wpforms-field-label | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#wpforms-4543-field_2-container > .wpforms-field-label")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 10 | click | id=wpforms-4543-field_2-container | 
    self.driver.find_element(By.ID, "wpforms-4543-field_2-container").click()
    # 11 | type | id=wpforms-4543-field_2 | Este es un comentario de prueba 
    self.driver.find_element(By.ID, "wpforms-4543-field_2").send_keys("Este es un comentario de prueba ")
    # 12 | selectFrame | index=2 | 
    self.driver.switch_to.frame(2)
    # 13 | click | css=.recaptcha-checkbox-border | 
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
    # 14 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 15 | type | name=g-recaptcha-hidden | 1
    self.driver.find_element(By.NAME, "g-recaptcha-hidden").send_keys("1")
    # 16 | click | id=wpforms-submit-4543 | 
    self.driver.find_element(By.ID, "wpforms-submit-4543").click()
    # 17 | close |  | 
    self.driver.close()
  
